### ISSUE TITLE
fsevents on non-macOS

### ISSUE THREAD

**Issue by sindrenm** [whirlwin/fript-web#6]
What it do, playa?

When installing dependencies on my Linux machine, the _fsevents_ module is removed from my generated _package-lock.json_ file. The reason for this, I suspect, is because _fsevents_ is a macOS-only package, its sole purpose being to tie into native OS X/macOS _FSEvents_ from Node. I tracked down the _[fsevents][]_ dependency to _[chokidar][]_, which in turn is required by _[nodemon][]_. Turns out that _fsevents_ is an [optional dependency][] in _chokidar_ – which I suppose it has to be since _fsevents_ won't even install on other platforms.

So what do we do with the dirty _package-lock.json_ files that are generated on non-macOS systems? It'll change depending on which system the dependencies are installed on since _fsevents_ will be removed from the lock files on some systems and added on other systems, and we wouldn't want to have that system-dependent change in version control …

Any ideas?

[fsevents]: https://github.com/whirlwin/fript-web/blob/acf3897f4bd3c135f4f5f7934c0ad5c407da4583/package-lock.json#L895
[chokidar]: https://github.com/whirlwin/fript-web/blob/acf3897f4bd3c135f4f5f7934c0ad5c407da4583/package-lock.json#L310
[nodemon]: https://github.com/whirlwin/fript-web/blob/acf3897f4bd3c135f4f5f7934c0ad5c407da4583/package-lock.json#L2499
[optional dependency]: https://github.com/paulmillr/chokidar/blob/cbdf25563cfff7f526e16ab4732b236e94be8f42/package.json#L44

**Comment by sindrenm** [comment]
Hmm … this is interesting:

> All optional dependencies should be included even if they're uninstallable on the current platform.
> — _https://docs.npmjs.com/files/package-lock.json#optional_

However, this doesn't seem to be the case for me.

**Comment by sindrenm** [comment]
Yeah, the issue has been raised on https://github.com/npm/npm/issues/17722 and still has no solution to date. :disappointed:

**Comment by whirlwin** [comment]
Strange. This does not seem to happen on Red Hat Enterprise Linux Server release 7.4 - reproducible builds should be a thing in 2017. :-P

**Comment by sindrenm** [comment]
Huh? How is that possible? Perhaps we're using different versions of npm then, me using one that has the package-lock bug and you using one that doesn't?

**Comment by whirlwin** [comment]
Hm. I'm back on macOS now, and the RHEL box is long gone. Doh!

**Comment by sindrenm** [comment]
😂😂😂
